//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranQuik.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public double _AppFontSize {
            get {
                return ((double)(this["_AppFontSize"]));
            }
            set {
                this["_AppFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial")]
        public string _AppFontFamily {
            get {
                return ((string)(this["_AppFontFamily"]));
            }
            set {
                this["_AppFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double _AppSaleMode {
            get {
                return ((double)(this["_AppSaleMode"]));
            }
            set {
                this["_AppSaleMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Development")]
        public string _AppID {
            get {
                return ((string)(this["_AppID"]));
            }
            set {
                this["_AppID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _AppSecMonitor {
            get {
                return ((bool)(this["_AppSecMonitor"]));
            }
            set {
                this["_AppSecMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _AppAllowImage {
            get {
                return ((bool)(this["_AppAllowImage"]));
            }
            set {
                this["_AppAllowImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _AppStatus {
            get {
                return ((bool)(this["_AppStatus"]));
            }
            set {
                this["_AppStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _LocalDbServer {
            get {
                return ((string)(this["_LocalDbServer"]));
            }
            set {
                this["_LocalDbServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _LocalDbPort {
            get {
                return ((int)(this["_LocalDbPort"]));
            }
            set {
                this["_LocalDbPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _LocalDbUsername {
            get {
                return ((string)(this["_LocalDbUsername"]));
            }
            set {
                this["_LocalDbUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _LocalDbPassword {
            get {
                return ((string)(this["_LocalDbPassword"]));
            }
            set {
                this["_LocalDbPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _LocalDbName {
            get {
                return ((string)(this["_LocalDbName"]));
            }
            set {
                this["_LocalDbName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _CloudDbServer {
            get {
                return ((string)(this["_CloudDbServer"]));
            }
            set {
                this["_CloudDbServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _CloudDbPort {
            get {
                return ((int)(this["_CloudDbPort"]));
            }
            set {
                this["_CloudDbPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _CloudDbUsername {
            get {
                return ((string)(this["_CloudDbUsername"]));
            }
            set {
                this["_CloudDbUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _CloudDbPassword {
            get {
                return ((string)(this["_CloudDbPassword"]));
            }
            set {
                this["_CloudDbPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _CloudDbName {
            get {
                return ((string)(this["_CloudDbName"]));
            }
            set {
                this["_CloudDbName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int _ComputerID {
            get {
                return ((int)(this["_ComputerID"]));
            }
            set {
                this["_ComputerID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _AppSecMonitorBorder {
            get {
                return ((int)(this["_AppSecMonitorBorder"]));
            }
            set {
                this["_AppSecMonitorBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _AppSecMonitorUrl {
            get {
                return ((string)(this["_AppSecMonitorUrl"]));
            }
            set {
                this["_AppSecMonitorUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _PrinterStatus {
            get {
                return ((bool)(this["_PrinterStatus"]));
            }
            set {
                this["_PrinterStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _PrinterName {
            get {
                return ((string)(this["_PrinterName"]));
            }
            set {
                this["_PrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime _LastSync {
            get {
                return ((global::System.DateTime)(this["_LastSync"]));
            }
            set {
                this["_LastSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _AutoSync {
            get {
                return ((bool)(this["_AutoSync"]));
            }
            set {
                this["_AutoSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _AppSecMonitorLoop {
            get {
                return ((int)(this["_AppSecMonitorLoop"]));
            }
            set {
                this["_AppSecMonitorLoop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _PrinterDevMode {
            get {
                return ((bool)(this["_PrinterDevMode"]));
            }
            set {
                this["_PrinterDevMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _PrinterMarginTop {
            get {
                return ((int)(this["_PrinterMarginTop"]));
            }
            set {
                this["_PrinterMarginTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _PrinterMarginBottom {
            get {
                return ((int)(this["_PrinterMarginBottom"]));
            }
            set {
                this["_PrinterMarginBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _PrinterMarginLeft {
            get {
                return ((int)(this["_PrinterMarginLeft"]));
            }
            set {
                this["_PrinterMarginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _PrinterMarginRight {
            get {
                return ((int)(this["_PrinterMarginRight"]));
            }
            set {
                this["_PrinterMarginRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _PrinterLogo {
            get {
                return ((string)(this["_PrinterLogo"]));
            }
            set {
                this["_PrinterLogo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ShopKey {
            get {
                return ((string)(this["_ShopKey"]));
            }
            set {
                this["_ShopKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ComputerName {
            get {
                return ((string)(this["_ComputerName"]));
            }
            set {
                this["_ComputerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _AnyDeskPath {
            get {
                return ((string)(this["_AnyDeskPath"]));
            }
            set {
                this["_AnyDeskPath"] = value;
            }
        }
    }
}
